version: '3.8'

services:
#  db:
#    build:
#      context: ./docker/postgres
#    container_name: db
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: ugur
#    ports:
#      - 5433:5432
#    volumes:
#      - ./docker/postgres/pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/ugur
#      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.37.61/:5432/ugur
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
